# Generated by Django 4.1.5 on 2023-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=10, null=True)),
                ("email_address", models.EmailField(max_length=50, null=True)),
                ("mbti", models.CharField(default="", max_length=10, null=True)),
                ("content", models.TextField()),
                ("introImage", models.ImageField(blank=True, upload_to="blog/images/")),
            ],
        ),
    ]
